################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Hardware/common/source/f2802x_adc.obj: ../Hardware/common/source/f2802x_adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_adc.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_asmfuncs.obj: ../Hardware/common/source/f2802x_asmfuncs.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_asmfuncs.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_codestartbranch.obj: ../Hardware/common/source/f2802x_codestartbranch.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_codestartbranch.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_comp.obj: ../Hardware/common/source/f2802x_comp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_comp.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_cputimers.obj: ../Hardware/common/source/f2802x_cputimers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_cputimers.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_defaultisr.obj: ../Hardware/common/source/f2802x_defaultisr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_defaultisr.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_ecap.obj: ../Hardware/common/source/f2802x_ecap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_ecap.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_epwm.obj: ../Hardware/common/source/f2802x_epwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_epwm.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_gpio.obj: ../Hardware/common/source/f2802x_gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_gpio.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_i2c.obj: ../Hardware/common/source/f2802x_i2c.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_i2c.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_osccomp.obj: ../Hardware/common/source/f2802x_osccomp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_osccomp.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_piectrl.obj: ../Hardware/common/source/f2802x_piectrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_piectrl.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_pievect.obj: ../Hardware/common/source/f2802x_pievect.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_pievect.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_sci.obj: ../Hardware/common/source/f2802x_sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_sci.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_spi.obj: ../Hardware/common/source/f2802x_spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_spi.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Hardware/common/source/f2802x_sysctrl.obj: ../Hardware/common/source/f2802x_sysctrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/bin/cl2000" -v28 -ml -mt --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-c2000_16.9.6.LTS/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/common/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/headers/include" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Lib" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Console" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Bsp" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Booster" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/Inverter" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Application/PIDCtrl" --include_path="D:/1.WORK/1.MiniUPS/software/workspace/MiniUPS/Hardware/libraries/math/IQmath/c28/include" --advice:performance=all -g --diag_suppress=232 --diag_suppress=10063 --diag_warning=225 --issue_remarks --verbose_diagnostics --quiet --preproc_with_compile --preproc_dependency="Hardware/common/source/f2802x_sysctrl.d_raw" --obj_directory="Hardware/common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


